version: "3"
services: 
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "vesper"
      POSTGRES_PASSWORD: "****"
    ports: 
      - 5432:5432
    volumes:
      - ./resources:/docker-entrypoint-initdb.d
  app:
    build: .
    depends_on: 
      - db
    ports: 
      - 3000:3000
